name: Analysis

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    analysis:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Run analysis
                shell: bash
                env:
                    GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
                    GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
                run: |
                    mkdir -p $HOME/.gradle
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > $HOME/.gradle/gradle.properties
                    scripts/analysis/analysis-wrapper.sh $GIT_USERNAME $GIT_TOKEN "master" $LOG_USERNAME $LOG_PASSWORD $DRONE_BUILD_NUMBER $DRONE_PULL_REQUEST
